config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  

  
  get 'about' => 'welcome#about'

  devise_for :users
  
  resources :movies
  
  root 'welcome#index'

end

app/models/genre.rb
# == Schema Information
#
# Table name: genres
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Genre < ActiveRecord::Base
  has_many :movie_genre
  has_many :movies, through: :movie_genres
end

app/models/movie.rb
# == Schema Information
#
# Table name: movies
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  rating     :string(255)
#  length     :string(255)
#  created_at :datetime
#  updated_at :datetime
#  spoiler    :string(255)
#  rotten_id  :integer
#  imdb_id    :integer
#  year       :integer
#  plot       :text
#

class Movie < ActiveRecord::Base
  paginates_per 10
  
  has_many :movie_genres
  has_many :genres, through: :movie_genres
end

app/models/movie_genre.rb
# == Schema Information
#
# Table name: movie_genres
#
#  id         :integer          not null, primary key
#  movie_id   :integer
#  genre_id   :integer
#  created_at :datetime
#  updated_at :datetime
#
# Indexes
#
#  index_movie_genres_on_genre_id  (genre_id)
#  index_movie_genres_on_movie_id  (movie_id)
#

class MovieGenre < ActiveRecord::Base
  belongs_to :movie
  belongs_to :genre
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime
#  updated_at             :datetime
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.order(:title).page(params[:page])
  end

  def show
    @movie = Movie.find(params[:id])
  end
  
  def new
    @movie = Movie.new
  end
  
  def create
    @movie = Movie.new(movie_params)
    @movie.save
    redirect_to '/movies'
  end
  
  private
  def movie_params
    
    params.require(:movie).permit(:title, :rating, :plot)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navigation.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Shonna Dorsey's Forum App - v1" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Spoiler Alert!', movies_path %></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active">
        <% if user_signed_in? %>
        <td><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></td>
        <% else %>
         <td><%= link_to 'Sign in', user_session_path %></td>
        <% end %>
        
      </li>
      <!--<li class="has-dropdown">
        <a href="#">Right Button Dropdown</a>
        <ul class="dropdown">
          <li><a href="#">First link in dropdown</a></li>
        </ul>
      </li>-->
    </ul>

    <!-- Left Nav Section -->
   <!-- <ul class="left">
      <li><a href="#">Left Nav Button</a></li>
    </ul>-->
  </section>
    </nav>
   
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "IMDB Lite" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    
    <%= render 'layouts/navigation' %>
    <div class = "row">
    <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
    
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
<% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this discussion from being saved:</h2>

      <ul>
        <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :plot %><br>
    <%= f.text_area :plot %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/index.html.erb
<h1>Movies Listing</h1>

<table>
      <thead>
    <tr>

      <th>Title</th>
      <th>Rating</th>
      <th>Length</th>
      <th>Year</th>
      
      
    </tr>
  </thead>


  <tbody>
    <% @movies.each do |movie| %>
        <tr>
          <td><%= link_to movie.title, movie %></td>
          <td><%= movie.rating %></td>
          <td><%= movie.length %></td>
          <td><%= movie.year %></td>
          
          
       
        </tr>
  </tbody>
      <% end %>

    
    

</table>
  <%= paginate @movies %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>

<ul>
  <li style="display:block"><strong>Rating: </strong> <%= @movie.rating %></li>
  <li style="display:block"><strong>Plot: </strong>
    <br>
    <%= @movie.plot %></li><p>
  <li style="display:block"><strong>Spoiler: </strong><font color = "red"><%= @movie.spoiler %></font></li>
 </ul>
<p>
  <%= link_to 'Back', movies_path %>

    

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome.</h1>
<body>
<div align="center">
<div class="row">
 <a data-orbit-link="headline-1" class="small button">
  Goto Slide 1
</a>
<a data-orbit-link="headline-2" class="small button">
  Goto Slide 2
</a>
<a data-orbit-link="headline-3" class="small button">
  Goto Slide 3
</a>
  <ul class="example-orbit-content" data-orbit>
  <li data-orbit-slide="headline-1">
    <div>
      <iframe width="560" height="315" src="//www.youtube.com/embed/hZ8Xj_I3aNU" frameborder="0" allowfullscreen></iframe>
    </div>
  </li>
  <li data-orbit-slide="headline-2">
    <div>
      <iframe width="560" height="315" src="//www.youtube.com/embed/hZ8Xj_I3aNU" frameborder="0" allowfullscreen></iframe>
    </div>
  </li>
  <li data-orbit-slide="headline-3">
    <div>
      <iframe width="560" height="315" src="//www.youtube.com/embed/hZ8Xj_I3aNU" frameborder="0" allowfullscreen></iframe>
    </div>
  </li>
</ul>
  </div>
  </div>
  <script src="js/vendor/jquery.js"></script>
<script src="js/foundation/foundation.js"></script>
<script src="js/foundation/foundation.orbit.js"></script>
</body>